# Generated by Django 5.1.1 on 2025-01-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.IntegerField(),
        ),
    ]
